/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "api.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(api_EmptyMessage, api_EmptyMessage, AUTO)


PB_BIND(api_APSettings, api_APSettings, AUTO)


PB_BIND(api_APStatus, api_APStatus, AUTO)


PB_BIND(api_APSettingsRequest, api_APSettingsRequest, AUTO)


PB_BIND(api_APStatusRequest, api_APStatusRequest, AUTO)


PB_BIND(api_Servo, api_Servo, AUTO)


PB_BIND(api_ServoSettings, api_ServoSettings, 2)


PB_BIND(api_ServoSettingsRequest, api_ServoSettingsRequest, AUTO)


PB_BIND(api_WifiNetwork, api_WifiNetwork, AUTO)


PB_BIND(api_WifiSettings, api_WifiSettings, 2)


PB_BIND(api_WifiSettingsRequest, api_WifiSettingsRequest, AUTO)


PB_BIND(api_WifiNetworkScan, api_WifiNetworkScan, AUTO)


PB_BIND(api_WifiNetworkList, api_WifiNetworkList, AUTO)


PB_BIND(api_WifiStatus, api_WifiStatus, AUTO)


PB_BIND(api_CameraSettings, api_CameraSettings, AUTO)


PB_BIND(api_CameraSettingsRequest, api_CameraSettingsRequest, AUTO)


PB_BIND(api_MDNSTxtRecord, api_MDNSTxtRecord, AUTO)


PB_BIND(api_MDNSServiceDef, api_MDNSServiceDef, 2)


PB_BIND(api_MDNSSettings, api_MDNSSettings, 2)


PB_BIND(api_MDNSStatus, api_MDNSStatus, 2)


PB_BIND(api_MDNSSettingsRequest, api_MDNSSettingsRequest, AUTO)


PB_BIND(api_MDNSStatusRequest, api_MDNSStatusRequest, AUTO)


PB_BIND(api_MDNSQueryRequest, api_MDNSQueryRequest, AUTO)


PB_BIND(api_MDNSQueryResult, api_MDNSQueryResult, AUTO)


PB_BIND(api_MDNSQueryResponse, api_MDNSQueryResponse, 2)


PB_BIND(api_PinConfig, api_PinConfig, AUTO)


PB_BIND(api_PeripheralSettings, api_PeripheralSettings, 2)


PB_BIND(api_PeripheralSettingsRequest, api_PeripheralSettingsRequest, AUTO)


PB_BIND(api_FileEntry, api_FileEntry, AUTO)


PB_BIND(api_FileList, api_FileList, AUTO)


PB_BIND(api_FileListRequest, api_FileListRequest, AUTO)


PB_BIND(api_FileDeleteRequest, api_FileDeleteRequest, AUTO)


PB_BIND(api_FileEditRequest, api_FileEditRequest, AUTO)


PB_BIND(api_FileMkdirRequest, api_FileMkdirRequest, AUTO)


PB_BIND(api_Request, api_Request, 2)


PB_BIND(api_Response, api_Response, 2)







