/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_API_API_PB_H_INCLUDED
#define PB_API_API_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _api_APProvisionMode {
    api_APProvisionMode_AP_MODE_ALWAYS = 0,
    api_APProvisionMode_AP_MODE_DISCONNECTED = 1,
    api_APProvisionMode_AP_MODE_NEVER = 2
} api_APProvisionMode;

typedef enum _api_APNetworkStatus {
    api_APNetworkStatus_AP_ACTIVE = 0,
    api_APNetworkStatus_AP_INACTIVE = 1,
    api_APNetworkStatus_AP_LINGERING = 2
} api_APNetworkStatus;

/* Struct definitions */
/* Empty message for endpoints which only needs a status */
typedef struct _api_EmptyMessage {
    char dummy_field;
} api_EmptyMessage;

typedef struct _api_APSettings {
    api_APProvisionMode provision_mode;
    char ssid[33];
    char password[64];
    uint32_t channel;
    bool ssid_hidden;
    uint32_t max_clients;
    uint32_t local_ip;
    uint32_t gateway_ip;
    uint32_t subnet_mask;
} api_APSettings;

typedef struct _api_APStatus {
    api_APNetworkStatus status;
    uint32_t ip_address;
    char mac_address[18];
    uint32_t station_num;
} api_APStatus;

/* Empty request types for GET-like operations */
typedef struct _api_APSettingsRequest {
    char dummy_field;
} api_APSettingsRequest;

typedef struct _api_APStatusRequest {
    char dummy_field;
} api_APStatusRequest;

typedef struct _api_Servo {
    float center_pwm;
    float direction;
    float center_angle;
    float conversion;
    char name[16];
} api_Servo;

typedef struct _api_ServoSettings {
    pb_size_t servos_count;
    api_Servo servos[12]; /* max 12 servos */
} api_ServoSettings;

typedef struct _api_ServoSettingsRequest {
    char dummy_field;
} api_ServoSettingsRequest;

typedef struct _api_WifiNetwork {
    char ssid[33];
    char password[65];
    bool static_ip_config;
    uint32_t local_ip;
    uint32_t gateway_ip;
    uint32_t subnet_mask;
    uint32_t dns_ip_1;
    uint32_t dns_ip_2;
} api_WifiNetwork;

typedef struct _api_WifiSettings {
    char hostname[33];
    bool priority_rssi;
    pb_size_t wifi_networks_count;
    api_WifiNetwork wifi_networks[5]; /* max 5 networks */
    uint32_t selected_network;
} api_WifiSettings;

typedef struct _api_WifiSettingsRequest {
    char dummy_field;
} api_WifiSettingsRequest;

/* WiFi scan result - single network found during scan */
typedef struct _api_WifiNetworkScan {
    int32_t rssi;
    char ssid[33];
    char bssid[18];
    uint32_t channel;
    uint32_t encryption_type;
} api_WifiNetworkScan;

/* Response for /api/wifi/networks endpoint */
typedef struct _api_WifiNetworkList {
    pb_size_t networks_count;
    struct _api_WifiNetworkScan *networks;
} api_WifiNetworkList;

/* Response for /api/wifi/sta/status endpoint */
typedef struct _api_WifiStatus {
    uint32_t status;
    uint32_t local_ip;
    char mac_address[18];
    int32_t rssi;
    char ssid[33];
    char bssid[18];
    uint32_t channel;
    uint32_t subnet_mask;
    uint32_t gateway_ip;
    uint32_t dns_ip_1;
    uint32_t dns_ip_2;
} api_WifiStatus;

typedef struct _api_CameraSettings {
    uint32_t pixformat;
    uint32_t framesize; /* 0-10 */
    uint32_t quality; /* 0-63 */
    int32_t brightness; /* -2 to 2 */
    int32_t contrast; /* -2 to 2 */
    int32_t saturation; /* -2 to 2 */
    int32_t sharpness; /* -2 to 2 */
    uint32_t denoise;
    uint32_t gainceiling;
    uint32_t whitebal;
    uint32_t special_effect; /* 0-6 */
    uint32_t wb_mode; /* 0-4 */
    uint32_t awb;
    uint32_t exposure_ctrl;
    uint32_t awb_gain;
    uint32_t gain_ctrl;
    uint32_t aec;
    uint32_t aec2;
    int32_t ae_level; /* -2 to 2 */
    uint32_t aec_value; /* 0-1200 */
    uint32_t agc;
    uint32_t agc_gain; /* 0-30 */
    uint32_t bpc;
    uint32_t wpc;
    uint32_t raw_gma;
    uint32_t lenc;
    uint32_t hmirror;
    uint32_t vflip;
    uint32_t dcw;
    uint32_t colorbar;
} api_CameraSettings;

typedef struct _api_CameraSettingsRequest {
    char dummy_field;
} api_CameraSettingsRequest;

typedef struct _api_MDNSTxtRecord {
    char key[32];
    char value[64];
} api_MDNSTxtRecord;

typedef struct _api_MDNSServiceDef {
    char service[16];
    char protocol[8];
    uint32_t port;
    pb_size_t txt_records_count;
    api_MDNSTxtRecord txt_records[4];
} api_MDNSServiceDef;

typedef struct _api_MDNSSettings {
    char hostname[33];
    char instance[64];
    pb_size_t services_count;
    api_MDNSServiceDef services[4];
    pb_size_t global_txt_records_count;
    api_MDNSTxtRecord global_txt_records[4];
} api_MDNSSettings;

typedef struct _api_MDNSStatus {
    bool started;
    char hostname[33];
    char instance[64];
    pb_size_t services_count;
    api_MDNSServiceDef services[4];
    pb_size_t global_txt_records_count;
    api_MDNSTxtRecord global_txt_records[4];
} api_MDNSStatus;

typedef struct _api_MDNSSettingsRequest {
    char dummy_field;
} api_MDNSSettingsRequest;

typedef struct _api_MDNSStatusRequest {
    char dummy_field;
} api_MDNSStatusRequest;

typedef struct _api_MDNSQueryRequest {
    char service[16];
    char protocol[8];
} api_MDNSQueryRequest;

typedef struct _api_MDNSQueryResult {
    char name[64];
    char ip[46];
    uint32_t port;
} api_MDNSQueryResult;

typedef struct _api_MDNSQueryResponse {
    pb_size_t services_count;
    api_MDNSQueryResult services[16];
} api_MDNSQueryResponse;

typedef struct _api_PinConfig {
    int32_t pin;
    char mode[16];
    char type[16];
    char role[16];
} api_PinConfig;

typedef struct _api_PeripheralSettings {
    int32_t sda;
    int32_t scl;
    int32_t frequency;
    pb_size_t pins_count;
    api_PinConfig pins[32];
} api_PeripheralSettings;

typedef struct _api_PeripheralSettingsRequest {
    char dummy_field;
} api_PeripheralSettingsRequest;

typedef struct _api_FileEntry {
    char name[64];
    bool is_directory;
    uint32_t size; /* Only for files */
    pb_size_t children_count;
    struct _api_FileEntry *children; /* Only for directories */
} api_FileEntry;

typedef struct _api_FileList {
    pb_size_t entries_count;
    struct _api_FileEntry *entries;
} api_FileList;

typedef struct _api_FileListRequest {
    char dummy_field;
} api_FileListRequest;

typedef struct _api_FileDeleteRequest {
    char path[128];
} api_FileDeleteRequest;

typedef struct _api_FileEditRequest {
    char path[128];
    pb_bytes_array_t *content;
} api_FileEditRequest;

typedef struct _api_FileMkdirRequest {
    char path[128];
} api_FileMkdirRequest;

/* Request wrapper for REST endpoints */
typedef struct _api_Request {
    pb_size_t which_payload;
    union _api_Request_payload {
        api_APSettings ap_settings;
        api_APSettingsRequest ap_settings_request;
        api_APStatusRequest ap_status_request;
        api_ServoSettings servo_settings;
        api_ServoSettingsRequest servo_settings_request;
        api_FileListRequest file_list_request;
        api_FileDeleteRequest file_delete_request;
        api_FileEditRequest file_edit_request;
        api_FileMkdirRequest file_mkdir_request;
        api_WifiSettings wifi_settings;
        api_WifiSettingsRequest wifi_settings_request;
        api_CameraSettings camera_settings;
        api_CameraSettingsRequest camera_settings_request;
        api_MDNSSettings mdns_settings;
        api_MDNSSettingsRequest mdns_settings_request;
        api_MDNSStatusRequest mdns_status_request;
        api_MDNSQueryRequest mdns_query_request;
        api_PeripheralSettings peripheral_settings;
        api_PeripheralSettingsRequest peripheral_settings_request;
    } payload;
} api_Request;

/* Response wrapper for REST endpoints */
typedef struct _api_Response {
    uint32_t status_code;
    char *error_message;
    pb_size_t which_payload;
    union _api_Response_payload {
        api_EmptyMessage empty_message;
        api_APSettings ap_settings;
        api_APStatus ap_status;
        api_ServoSettings servo_settings;
        api_FileList file_list;
        api_WifiSettings wifi_settings;
        api_WifiNetworkList wifi_network_list;
        api_WifiStatus wifi_status;
        api_CameraSettings camera_settings;
        api_MDNSSettings mdns_settings;
        api_MDNSStatus mdns_status;
        api_MDNSQueryResponse mdns_query_response;
        api_PeripheralSettings peripheral_settings;
    } payload;
} api_Response;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _api_APProvisionMode_MIN api_APProvisionMode_AP_MODE_ALWAYS
#define _api_APProvisionMode_MAX api_APProvisionMode_AP_MODE_NEVER
#define _api_APProvisionMode_ARRAYSIZE ((api_APProvisionMode)(api_APProvisionMode_AP_MODE_NEVER+1))

#define _api_APNetworkStatus_MIN api_APNetworkStatus_AP_ACTIVE
#define _api_APNetworkStatus_MAX api_APNetworkStatus_AP_LINGERING
#define _api_APNetworkStatus_ARRAYSIZE ((api_APNetworkStatus)(api_APNetworkStatus_AP_LINGERING+1))


#define api_APSettings_provision_mode_ENUMTYPE api_APProvisionMode

#define api_APStatus_status_ENUMTYPE api_APNetworkStatus



































/* Initializer values for message structs */
#define api_EmptyMessage_init_default            {0}
#define api_APSettings_init_default              {_api_APProvisionMode_MIN, "", "", 0, 0, 0, 0, 0, 0}
#define api_APStatus_init_default                {_api_APNetworkStatus_MIN, 0, "", 0}
#define api_APSettingsRequest_init_default       {0}
#define api_APStatusRequest_init_default         {0}
#define api_Servo_init_default                   {0, 0, 0, 0, ""}
#define api_ServoSettings_init_default           {0, {api_Servo_init_default, api_Servo_init_default, api_Servo_init_default, api_Servo_init_default, api_Servo_init_default, api_Servo_init_default, api_Servo_init_default, api_Servo_init_default, api_Servo_init_default, api_Servo_init_default, api_Servo_init_default, api_Servo_init_default}}
#define api_ServoSettingsRequest_init_default    {0}
#define api_WifiNetwork_init_default             {"", "", 0, 0, 0, 0, 0, 0}
#define api_WifiSettings_init_default            {"", 0, 0, {api_WifiNetwork_init_default, api_WifiNetwork_init_default, api_WifiNetwork_init_default, api_WifiNetwork_init_default, api_WifiNetwork_init_default}, 0}
#define api_WifiSettingsRequest_init_default     {0}
#define api_WifiNetworkScan_init_default         {0, "", "", 0, 0}
#define api_WifiNetworkList_init_default         {0, NULL}
#define api_WifiStatus_init_default              {0, 0, "", 0, "", "", 0, 0, 0, 0, 0}
#define api_CameraSettings_init_default          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define api_CameraSettingsRequest_init_default   {0}
#define api_MDNSTxtRecord_init_default           {"", ""}
#define api_MDNSServiceDef_init_default          {"", "", 0, 0, {api_MDNSTxtRecord_init_default, api_MDNSTxtRecord_init_default, api_MDNSTxtRecord_init_default, api_MDNSTxtRecord_init_default}}
#define api_MDNSSettings_init_default            {"", "", 0, {api_MDNSServiceDef_init_default, api_MDNSServiceDef_init_default, api_MDNSServiceDef_init_default, api_MDNSServiceDef_init_default}, 0, {api_MDNSTxtRecord_init_default, api_MDNSTxtRecord_init_default, api_MDNSTxtRecord_init_default, api_MDNSTxtRecord_init_default}}
#define api_MDNSStatus_init_default              {0, "", "", 0, {api_MDNSServiceDef_init_default, api_MDNSServiceDef_init_default, api_MDNSServiceDef_init_default, api_MDNSServiceDef_init_default}, 0, {api_MDNSTxtRecord_init_default, api_MDNSTxtRecord_init_default, api_MDNSTxtRecord_init_default, api_MDNSTxtRecord_init_default}}
#define api_MDNSSettingsRequest_init_default     {0}
#define api_MDNSStatusRequest_init_default       {0}
#define api_MDNSQueryRequest_init_default        {"", ""}
#define api_MDNSQueryResult_init_default         {"", "", 0}
#define api_MDNSQueryResponse_init_default       {0, {api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default, api_MDNSQueryResult_init_default}}
#define api_PinConfig_init_default               {0, "", "", ""}
#define api_PeripheralSettings_init_default      {0, 0, 0, 0, {api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default, api_PinConfig_init_default}}
#define api_PeripheralSettingsRequest_init_default {0}
#define api_FileEntry_init_default               {"", 0, 0, 0, NULL}
#define api_FileList_init_default                {0, NULL}
#define api_FileListRequest_init_default         {0}
#define api_FileDeleteRequest_init_default       {""}
#define api_FileEditRequest_init_default         {"", NULL}
#define api_FileMkdirRequest_init_default        {""}
#define api_Request_init_default                 {0, {api_APSettings_init_default}}
#define api_Response_init_default                {0, NULL, 0, {api_EmptyMessage_init_default}}
#define api_EmptyMessage_init_zero               {0}
#define api_APSettings_init_zero                 {_api_APProvisionMode_MIN, "", "", 0, 0, 0, 0, 0, 0}
#define api_APStatus_init_zero                   {_api_APNetworkStatus_MIN, 0, "", 0}
#define api_APSettingsRequest_init_zero          {0}
#define api_APStatusRequest_init_zero            {0}
#define api_Servo_init_zero                      {0, 0, 0, 0, ""}
#define api_ServoSettings_init_zero              {0, {api_Servo_init_zero, api_Servo_init_zero, api_Servo_init_zero, api_Servo_init_zero, api_Servo_init_zero, api_Servo_init_zero, api_Servo_init_zero, api_Servo_init_zero, api_Servo_init_zero, api_Servo_init_zero, api_Servo_init_zero, api_Servo_init_zero}}
#define api_ServoSettingsRequest_init_zero       {0}
#define api_WifiNetwork_init_zero                {"", "", 0, 0, 0, 0, 0, 0}
#define api_WifiSettings_init_zero               {"", 0, 0, {api_WifiNetwork_init_zero, api_WifiNetwork_init_zero, api_WifiNetwork_init_zero, api_WifiNetwork_init_zero, api_WifiNetwork_init_zero}, 0}
#define api_WifiSettingsRequest_init_zero        {0}
#define api_WifiNetworkScan_init_zero            {0, "", "", 0, 0}
#define api_WifiNetworkList_init_zero            {0, NULL}
#define api_WifiStatus_init_zero                 {0, 0, "", 0, "", "", 0, 0, 0, 0, 0}
#define api_CameraSettings_init_zero             {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define api_CameraSettingsRequest_init_zero      {0}
#define api_MDNSTxtRecord_init_zero              {"", ""}
#define api_MDNSServiceDef_init_zero             {"", "", 0, 0, {api_MDNSTxtRecord_init_zero, api_MDNSTxtRecord_init_zero, api_MDNSTxtRecord_init_zero, api_MDNSTxtRecord_init_zero}}
#define api_MDNSSettings_init_zero               {"", "", 0, {api_MDNSServiceDef_init_zero, api_MDNSServiceDef_init_zero, api_MDNSServiceDef_init_zero, api_MDNSServiceDef_init_zero}, 0, {api_MDNSTxtRecord_init_zero, api_MDNSTxtRecord_init_zero, api_MDNSTxtRecord_init_zero, api_MDNSTxtRecord_init_zero}}
#define api_MDNSStatus_init_zero                 {0, "", "", 0, {api_MDNSServiceDef_init_zero, api_MDNSServiceDef_init_zero, api_MDNSServiceDef_init_zero, api_MDNSServiceDef_init_zero}, 0, {api_MDNSTxtRecord_init_zero, api_MDNSTxtRecord_init_zero, api_MDNSTxtRecord_init_zero, api_MDNSTxtRecord_init_zero}}
#define api_MDNSSettingsRequest_init_zero        {0}
#define api_MDNSStatusRequest_init_zero          {0}
#define api_MDNSQueryRequest_init_zero           {"", ""}
#define api_MDNSQueryResult_init_zero            {"", "", 0}
#define api_MDNSQueryResponse_init_zero          {0, {api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero, api_MDNSQueryResult_init_zero}}
#define api_PinConfig_init_zero                  {0, "", "", ""}
#define api_PeripheralSettings_init_zero         {0, 0, 0, 0, {api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero, api_PinConfig_init_zero}}
#define api_PeripheralSettingsRequest_init_zero  {0}
#define api_FileEntry_init_zero                  {"", 0, 0, 0, NULL}
#define api_FileList_init_zero                   {0, NULL}
#define api_FileListRequest_init_zero            {0}
#define api_FileDeleteRequest_init_zero          {""}
#define api_FileEditRequest_init_zero            {"", NULL}
#define api_FileMkdirRequest_init_zero           {""}
#define api_Request_init_zero                    {0, {api_APSettings_init_zero}}
#define api_Response_init_zero                   {0, NULL, 0, {api_EmptyMessage_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define api_APSettings_provision_mode_tag        1
#define api_APSettings_ssid_tag                  2
#define api_APSettings_password_tag              3
#define api_APSettings_channel_tag               4
#define api_APSettings_ssid_hidden_tag           5
#define api_APSettings_max_clients_tag           6
#define api_APSettings_local_ip_tag              7
#define api_APSettings_gateway_ip_tag            8
#define api_APSettings_subnet_mask_tag           9
#define api_APStatus_status_tag                  1
#define api_APStatus_ip_address_tag              2
#define api_APStatus_mac_address_tag             3
#define api_APStatus_station_num_tag             4
#define api_Servo_center_pwm_tag                 1
#define api_Servo_direction_tag                  2
#define api_Servo_center_angle_tag               3
#define api_Servo_conversion_tag                 4
#define api_Servo_name_tag                       5
#define api_ServoSettings_servos_tag             1
#define api_WifiNetwork_ssid_tag                 1
#define api_WifiNetwork_password_tag             2
#define api_WifiNetwork_static_ip_config_tag     3
#define api_WifiNetwork_local_ip_tag             4
#define api_WifiNetwork_gateway_ip_tag           5
#define api_WifiNetwork_subnet_mask_tag          6
#define api_WifiNetwork_dns_ip_1_tag             7
#define api_WifiNetwork_dns_ip_2_tag             8
#define api_WifiSettings_hostname_tag            1
#define api_WifiSettings_priority_rssi_tag       2
#define api_WifiSettings_wifi_networks_tag       3
#define api_WifiSettings_selected_network_tag    4
#define api_WifiNetworkScan_rssi_tag             1
#define api_WifiNetworkScan_ssid_tag             2
#define api_WifiNetworkScan_bssid_tag            3
#define api_WifiNetworkScan_channel_tag          4
#define api_WifiNetworkScan_encryption_type_tag  5
#define api_WifiNetworkList_networks_tag         1
#define api_WifiStatus_status_tag                1
#define api_WifiStatus_local_ip_tag              2
#define api_WifiStatus_mac_address_tag           3
#define api_WifiStatus_rssi_tag                  4
#define api_WifiStatus_ssid_tag                  5
#define api_WifiStatus_bssid_tag                 6
#define api_WifiStatus_channel_tag               7
#define api_WifiStatus_subnet_mask_tag           8
#define api_WifiStatus_gateway_ip_tag            9
#define api_WifiStatus_dns_ip_1_tag              10
#define api_WifiStatus_dns_ip_2_tag              11
#define api_CameraSettings_pixformat_tag         1
#define api_CameraSettings_framesize_tag         2
#define api_CameraSettings_quality_tag           3
#define api_CameraSettings_brightness_tag        4
#define api_CameraSettings_contrast_tag          5
#define api_CameraSettings_saturation_tag        6
#define api_CameraSettings_sharpness_tag         7
#define api_CameraSettings_denoise_tag           8
#define api_CameraSettings_gainceiling_tag       9
#define api_CameraSettings_whitebal_tag          10
#define api_CameraSettings_special_effect_tag    11
#define api_CameraSettings_wb_mode_tag           12
#define api_CameraSettings_awb_tag               13
#define api_CameraSettings_exposure_ctrl_tag     14
#define api_CameraSettings_awb_gain_tag          15
#define api_CameraSettings_gain_ctrl_tag         16
#define api_CameraSettings_aec_tag               17
#define api_CameraSettings_aec2_tag              18
#define api_CameraSettings_ae_level_tag          19
#define api_CameraSettings_aec_value_tag         20
#define api_CameraSettings_agc_tag               21
#define api_CameraSettings_agc_gain_tag          22
#define api_CameraSettings_bpc_tag               23
#define api_CameraSettings_wpc_tag               24
#define api_CameraSettings_raw_gma_tag           25
#define api_CameraSettings_lenc_tag              26
#define api_CameraSettings_hmirror_tag           27
#define api_CameraSettings_vflip_tag             28
#define api_CameraSettings_dcw_tag               29
#define api_CameraSettings_colorbar_tag          30
#define api_MDNSTxtRecord_key_tag                1
#define api_MDNSTxtRecord_value_tag              2
#define api_MDNSServiceDef_service_tag           1
#define api_MDNSServiceDef_protocol_tag          2
#define api_MDNSServiceDef_port_tag              3
#define api_MDNSServiceDef_txt_records_tag       4
#define api_MDNSSettings_hostname_tag            1
#define api_MDNSSettings_instance_tag            2
#define api_MDNSSettings_services_tag            3
#define api_MDNSSettings_global_txt_records_tag  4
#define api_MDNSStatus_started_tag               1
#define api_MDNSStatus_hostname_tag              2
#define api_MDNSStatus_instance_tag              3
#define api_MDNSStatus_services_tag              4
#define api_MDNSStatus_global_txt_records_tag    5
#define api_MDNSQueryRequest_service_tag         1
#define api_MDNSQueryRequest_protocol_tag        2
#define api_MDNSQueryResult_name_tag             1
#define api_MDNSQueryResult_ip_tag               2
#define api_MDNSQueryResult_port_tag             3
#define api_MDNSQueryResponse_services_tag       1
#define api_PinConfig_pin_tag                    1
#define api_PinConfig_mode_tag                   2
#define api_PinConfig_type_tag                   3
#define api_PinConfig_role_tag                   4
#define api_PeripheralSettings_sda_tag           1
#define api_PeripheralSettings_scl_tag           2
#define api_PeripheralSettings_frequency_tag     3
#define api_PeripheralSettings_pins_tag          4
#define api_FileEntry_name_tag                   1
#define api_FileEntry_is_directory_tag           2
#define api_FileEntry_size_tag                   3
#define api_FileEntry_children_tag               4
#define api_FileList_entries_tag                 1
#define api_FileDeleteRequest_path_tag           1
#define api_FileEditRequest_path_tag             1
#define api_FileEditRequest_content_tag          2
#define api_FileMkdirRequest_path_tag            1
#define api_Request_ap_settings_tag              10
#define api_Request_ap_settings_request_tag      11
#define api_Request_ap_status_request_tag        12
#define api_Request_servo_settings_tag           20
#define api_Request_servo_settings_request_tag   21
#define api_Request_file_list_request_tag        30
#define api_Request_file_delete_request_tag      31
#define api_Request_file_edit_request_tag        32
#define api_Request_file_mkdir_request_tag       33
#define api_Request_wifi_settings_tag            40
#define api_Request_wifi_settings_request_tag    41
#define api_Request_camera_settings_tag          50
#define api_Request_camera_settings_request_tag  51
#define api_Request_mdns_settings_tag            60
#define api_Request_mdns_settings_request_tag    61
#define api_Request_mdns_status_request_tag      62
#define api_Request_mdns_query_request_tag       63
#define api_Request_peripheral_settings_tag      70
#define api_Request_peripheral_settings_request_tag 71
#define api_Response_status_code_tag             1
#define api_Response_error_message_tag           2
#define api_Response_empty_message_tag           5
#define api_Response_ap_settings_tag             10
#define api_Response_ap_status_tag               11
#define api_Response_servo_settings_tag          20
#define api_Response_file_list_tag               30
#define api_Response_wifi_settings_tag           40
#define api_Response_wifi_network_list_tag       41
#define api_Response_wifi_status_tag             42
#define api_Response_camera_settings_tag         50
#define api_Response_mdns_settings_tag           60
#define api_Response_mdns_status_tag             61
#define api_Response_mdns_query_response_tag     62
#define api_Response_peripheral_settings_tag     70

/* Struct field encoding specification for nanopb */
#define api_EmptyMessage_FIELDLIST(X, a) \

#define api_EmptyMessage_CALLBACK NULL
#define api_EmptyMessage_DEFAULT NULL

#define api_APSettings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    provision_mode,    1) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              2) \
X(a, STATIC,   SINGULAR, STRING,   password,          3) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           4) \
X(a, STATIC,   SINGULAR, BOOL,     ssid_hidden,       5) \
X(a, STATIC,   SINGULAR, UINT32,   max_clients,       6) \
X(a, STATIC,   SINGULAR, UINT32,   local_ip,          7) \
X(a, STATIC,   SINGULAR, UINT32,   gateway_ip,        8) \
X(a, STATIC,   SINGULAR, UINT32,   subnet_mask,       9)
#define api_APSettings_CALLBACK NULL
#define api_APSettings_DEFAULT NULL

#define api_APStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   SINGULAR, UINT32,   ip_address,        2) \
X(a, STATIC,   SINGULAR, STRING,   mac_address,       3) \
X(a, STATIC,   SINGULAR, UINT32,   station_num,       4)
#define api_APStatus_CALLBACK NULL
#define api_APStatus_DEFAULT NULL

#define api_APSettingsRequest_FIELDLIST(X, a) \

#define api_APSettingsRequest_CALLBACK NULL
#define api_APSettingsRequest_DEFAULT NULL

#define api_APStatusRequest_FIELDLIST(X, a) \

#define api_APStatusRequest_CALLBACK NULL
#define api_APStatusRequest_DEFAULT NULL

#define api_Servo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    center_pwm,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    direction,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    center_angle,      3) \
X(a, STATIC,   SINGULAR, FLOAT,    conversion,        4) \
X(a, STATIC,   SINGULAR, STRING,   name,              5)
#define api_Servo_CALLBACK NULL
#define api_Servo_DEFAULT NULL

#define api_ServoSettings_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  servos,            1)
#define api_ServoSettings_CALLBACK NULL
#define api_ServoSettings_DEFAULT NULL
#define api_ServoSettings_servos_MSGTYPE api_Servo

#define api_ServoSettingsRequest_FIELDLIST(X, a) \

#define api_ServoSettingsRequest_CALLBACK NULL
#define api_ServoSettingsRequest_DEFAULT NULL

#define api_WifiNetwork_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              1) \
X(a, STATIC,   SINGULAR, STRING,   password,          2) \
X(a, STATIC,   SINGULAR, BOOL,     static_ip_config,   3) \
X(a, STATIC,   SINGULAR, UINT32,   local_ip,          4) \
X(a, STATIC,   SINGULAR, UINT32,   gateway_ip,        5) \
X(a, STATIC,   SINGULAR, UINT32,   subnet_mask,       6) \
X(a, STATIC,   SINGULAR, UINT32,   dns_ip_1,          7) \
X(a, STATIC,   SINGULAR, UINT32,   dns_ip_2,          8)
#define api_WifiNetwork_CALLBACK NULL
#define api_WifiNetwork_DEFAULT NULL

#define api_WifiSettings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   hostname,          1) \
X(a, STATIC,   SINGULAR, BOOL,     priority_rssi,     2) \
X(a, STATIC,   REPEATED, MESSAGE,  wifi_networks,     3) \
X(a, STATIC,   SINGULAR, UINT32,   selected_network,   4)
#define api_WifiSettings_CALLBACK NULL
#define api_WifiSettings_DEFAULT NULL
#define api_WifiSettings_wifi_networks_MSGTYPE api_WifiNetwork

#define api_WifiSettingsRequest_FIELDLIST(X, a) \

#define api_WifiSettingsRequest_CALLBACK NULL
#define api_WifiSettingsRequest_DEFAULT NULL

#define api_WifiNetworkScan_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              1) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              2) \
X(a, STATIC,   SINGULAR, STRING,   bssid,             3) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           4) \
X(a, STATIC,   SINGULAR, UINT32,   encryption_type,   5)
#define api_WifiNetworkScan_CALLBACK NULL
#define api_WifiNetworkScan_DEFAULT NULL

#define api_WifiNetworkList_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  networks,          1)
#define api_WifiNetworkList_CALLBACK NULL
#define api_WifiNetworkList_DEFAULT NULL
#define api_WifiNetworkList_networks_MSGTYPE api_WifiNetworkScan

#define api_WifiStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   status,            1) \
X(a, STATIC,   SINGULAR, UINT32,   local_ip,          2) \
X(a, STATIC,   SINGULAR, STRING,   mac_address,       3) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              4) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              5) \
X(a, STATIC,   SINGULAR, STRING,   bssid,             6) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           7) \
X(a, STATIC,   SINGULAR, UINT32,   subnet_mask,       8) \
X(a, STATIC,   SINGULAR, UINT32,   gateway_ip,        9) \
X(a, STATIC,   SINGULAR, UINT32,   dns_ip_1,         10) \
X(a, STATIC,   SINGULAR, UINT32,   dns_ip_2,         11)
#define api_WifiStatus_CALLBACK NULL
#define api_WifiStatus_DEFAULT NULL

#define api_CameraSettings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pixformat,         1) \
X(a, STATIC,   SINGULAR, UINT32,   framesize,         2) \
X(a, STATIC,   SINGULAR, UINT32,   quality,           3) \
X(a, STATIC,   SINGULAR, INT32,    brightness,        4) \
X(a, STATIC,   SINGULAR, INT32,    contrast,          5) \
X(a, STATIC,   SINGULAR, INT32,    saturation,        6) \
X(a, STATIC,   SINGULAR, INT32,    sharpness,         7) \
X(a, STATIC,   SINGULAR, UINT32,   denoise,           8) \
X(a, STATIC,   SINGULAR, UINT32,   gainceiling,       9) \
X(a, STATIC,   SINGULAR, UINT32,   whitebal,         10) \
X(a, STATIC,   SINGULAR, UINT32,   special_effect,   11) \
X(a, STATIC,   SINGULAR, UINT32,   wb_mode,          12) \
X(a, STATIC,   SINGULAR, UINT32,   awb,              13) \
X(a, STATIC,   SINGULAR, UINT32,   exposure_ctrl,    14) \
X(a, STATIC,   SINGULAR, UINT32,   awb_gain,         15) \
X(a, STATIC,   SINGULAR, UINT32,   gain_ctrl,        16) \
X(a, STATIC,   SINGULAR, UINT32,   aec,              17) \
X(a, STATIC,   SINGULAR, UINT32,   aec2,             18) \
X(a, STATIC,   SINGULAR, INT32,    ae_level,         19) \
X(a, STATIC,   SINGULAR, UINT32,   aec_value,        20) \
X(a, STATIC,   SINGULAR, UINT32,   agc,              21) \
X(a, STATIC,   SINGULAR, UINT32,   agc_gain,         22) \
X(a, STATIC,   SINGULAR, UINT32,   bpc,              23) \
X(a, STATIC,   SINGULAR, UINT32,   wpc,              24) \
X(a, STATIC,   SINGULAR, UINT32,   raw_gma,          25) \
X(a, STATIC,   SINGULAR, UINT32,   lenc,             26) \
X(a, STATIC,   SINGULAR, UINT32,   hmirror,          27) \
X(a, STATIC,   SINGULAR, UINT32,   vflip,            28) \
X(a, STATIC,   SINGULAR, UINT32,   dcw,              29) \
X(a, STATIC,   SINGULAR, UINT32,   colorbar,         30)
#define api_CameraSettings_CALLBACK NULL
#define api_CameraSettings_DEFAULT NULL

#define api_CameraSettingsRequest_FIELDLIST(X, a) \

#define api_CameraSettingsRequest_CALLBACK NULL
#define api_CameraSettingsRequest_DEFAULT NULL

#define api_MDNSTxtRecord_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2)
#define api_MDNSTxtRecord_CALLBACK NULL
#define api_MDNSTxtRecord_DEFAULT NULL

#define api_MDNSServiceDef_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   service,           1) \
X(a, STATIC,   SINGULAR, STRING,   protocol,          2) \
X(a, STATIC,   SINGULAR, UINT32,   port,              3) \
X(a, STATIC,   REPEATED, MESSAGE,  txt_records,       4)
#define api_MDNSServiceDef_CALLBACK NULL
#define api_MDNSServiceDef_DEFAULT NULL
#define api_MDNSServiceDef_txt_records_MSGTYPE api_MDNSTxtRecord

#define api_MDNSSettings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   hostname,          1) \
X(a, STATIC,   SINGULAR, STRING,   instance,          2) \
X(a, STATIC,   REPEATED, MESSAGE,  services,          3) \
X(a, STATIC,   REPEATED, MESSAGE,  global_txt_records,   4)
#define api_MDNSSettings_CALLBACK NULL
#define api_MDNSSettings_DEFAULT NULL
#define api_MDNSSettings_services_MSGTYPE api_MDNSServiceDef
#define api_MDNSSettings_global_txt_records_MSGTYPE api_MDNSTxtRecord

#define api_MDNSStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     started,           1) \
X(a, STATIC,   SINGULAR, STRING,   hostname,          2) \
X(a, STATIC,   SINGULAR, STRING,   instance,          3) \
X(a, STATIC,   REPEATED, MESSAGE,  services,          4) \
X(a, STATIC,   REPEATED, MESSAGE,  global_txt_records,   5)
#define api_MDNSStatus_CALLBACK NULL
#define api_MDNSStatus_DEFAULT NULL
#define api_MDNSStatus_services_MSGTYPE api_MDNSServiceDef
#define api_MDNSStatus_global_txt_records_MSGTYPE api_MDNSTxtRecord

#define api_MDNSSettingsRequest_FIELDLIST(X, a) \

#define api_MDNSSettingsRequest_CALLBACK NULL
#define api_MDNSSettingsRequest_DEFAULT NULL

#define api_MDNSStatusRequest_FIELDLIST(X, a) \

#define api_MDNSStatusRequest_CALLBACK NULL
#define api_MDNSStatusRequest_DEFAULT NULL

#define api_MDNSQueryRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   service,           1) \
X(a, STATIC,   SINGULAR, STRING,   protocol,          2)
#define api_MDNSQueryRequest_CALLBACK NULL
#define api_MDNSQueryRequest_DEFAULT NULL

#define api_MDNSQueryResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, STRING,   ip,                2) \
X(a, STATIC,   SINGULAR, UINT32,   port,              3)
#define api_MDNSQueryResult_CALLBACK NULL
#define api_MDNSQueryResult_DEFAULT NULL

#define api_MDNSQueryResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  services,          1)
#define api_MDNSQueryResponse_CALLBACK NULL
#define api_MDNSQueryResponse_DEFAULT NULL
#define api_MDNSQueryResponse_services_MSGTYPE api_MDNSQueryResult

#define api_PinConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    pin,               1) \
X(a, STATIC,   SINGULAR, STRING,   mode,              2) \
X(a, STATIC,   SINGULAR, STRING,   type,              3) \
X(a, STATIC,   SINGULAR, STRING,   role,              4)
#define api_PinConfig_CALLBACK NULL
#define api_PinConfig_DEFAULT NULL

#define api_PeripheralSettings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    sda,               1) \
X(a, STATIC,   SINGULAR, INT32,    scl,               2) \
X(a, STATIC,   SINGULAR, INT32,    frequency,         3) \
X(a, STATIC,   REPEATED, MESSAGE,  pins,              4)
#define api_PeripheralSettings_CALLBACK NULL
#define api_PeripheralSettings_DEFAULT NULL
#define api_PeripheralSettings_pins_MSGTYPE api_PinConfig

#define api_PeripheralSettingsRequest_FIELDLIST(X, a) \

#define api_PeripheralSettingsRequest_CALLBACK NULL
#define api_PeripheralSettingsRequest_DEFAULT NULL

#define api_FileEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, BOOL,     is_directory,      2) \
X(a, STATIC,   SINGULAR, UINT32,   size,              3) \
X(a, POINTER,  REPEATED, MESSAGE,  children,          4)
#define api_FileEntry_CALLBACK NULL
#define api_FileEntry_DEFAULT NULL
#define api_FileEntry_children_MSGTYPE api_FileEntry

#define api_FileList_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  entries,           1)
#define api_FileList_CALLBACK NULL
#define api_FileList_DEFAULT NULL
#define api_FileList_entries_MSGTYPE api_FileEntry

#define api_FileListRequest_FIELDLIST(X, a) \

#define api_FileListRequest_CALLBACK NULL
#define api_FileListRequest_DEFAULT NULL

#define api_FileDeleteRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   path,              1)
#define api_FileDeleteRequest_CALLBACK NULL
#define api_FileDeleteRequest_DEFAULT NULL

#define api_FileEditRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   path,              1) \
X(a, POINTER,  SINGULAR, BYTES,    content,           2)
#define api_FileEditRequest_CALLBACK NULL
#define api_FileEditRequest_DEFAULT NULL

#define api_FileMkdirRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   path,              1)
#define api_FileMkdirRequest_CALLBACK NULL
#define api_FileMkdirRequest_DEFAULT NULL

#define api_Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ap_settings,payload.ap_settings),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ap_settings_request,payload.ap_settings_request),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ap_status_request,payload.ap_status_request),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,servo_settings,payload.servo_settings),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,servo_settings_request,payload.servo_settings_request),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,file_list_request,payload.file_list_request),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,file_delete_request,payload.file_delete_request),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,file_edit_request,payload.file_edit_request),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,file_mkdir_request,payload.file_mkdir_request),  33) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,wifi_settings,payload.wifi_settings),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,wifi_settings_request,payload.wifi_settings_request),  41) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,camera_settings,payload.camera_settings),  50) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,camera_settings_request,payload.camera_settings_request),  51) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mdns_settings,payload.mdns_settings),  60) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mdns_settings_request,payload.mdns_settings_request),  61) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mdns_status_request,payload.mdns_status_request),  62) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mdns_query_request,payload.mdns_query_request),  63) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,peripheral_settings,payload.peripheral_settings),  70) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,peripheral_settings_request,payload.peripheral_settings_request),  71)
#define api_Request_CALLBACK NULL
#define api_Request_DEFAULT NULL
#define api_Request_payload_ap_settings_MSGTYPE api_APSettings
#define api_Request_payload_ap_settings_request_MSGTYPE api_APSettingsRequest
#define api_Request_payload_ap_status_request_MSGTYPE api_APStatusRequest
#define api_Request_payload_servo_settings_MSGTYPE api_ServoSettings
#define api_Request_payload_servo_settings_request_MSGTYPE api_ServoSettingsRequest
#define api_Request_payload_file_list_request_MSGTYPE api_FileListRequest
#define api_Request_payload_file_delete_request_MSGTYPE api_FileDeleteRequest
#define api_Request_payload_file_edit_request_MSGTYPE api_FileEditRequest
#define api_Request_payload_file_mkdir_request_MSGTYPE api_FileMkdirRequest
#define api_Request_payload_wifi_settings_MSGTYPE api_WifiSettings
#define api_Request_payload_wifi_settings_request_MSGTYPE api_WifiSettingsRequest
#define api_Request_payload_camera_settings_MSGTYPE api_CameraSettings
#define api_Request_payload_camera_settings_request_MSGTYPE api_CameraSettingsRequest
#define api_Request_payload_mdns_settings_MSGTYPE api_MDNSSettings
#define api_Request_payload_mdns_settings_request_MSGTYPE api_MDNSSettingsRequest
#define api_Request_payload_mdns_status_request_MSGTYPE api_MDNSStatusRequest
#define api_Request_payload_mdns_query_request_MSGTYPE api_MDNSQueryRequest
#define api_Request_payload_peripheral_settings_MSGTYPE api_PeripheralSettings
#define api_Request_payload_peripheral_settings_request_MSGTYPE api_PeripheralSettingsRequest

#define api_Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   status_code,       1) \
X(a, POINTER,  SINGULAR, STRING,   error_message,     2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,empty_message,payload.empty_message),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ap_settings,payload.ap_settings),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ap_status,payload.ap_status),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,servo_settings,payload.servo_settings),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,file_list,payload.file_list),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,wifi_settings,payload.wifi_settings),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,wifi_network_list,payload.wifi_network_list),  41) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,wifi_status,payload.wifi_status),  42) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,camera_settings,payload.camera_settings),  50) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mdns_settings,payload.mdns_settings),  60) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mdns_status,payload.mdns_status),  61) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mdns_query_response,payload.mdns_query_response),  62) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,peripheral_settings,payload.peripheral_settings),  70)
#define api_Response_CALLBACK NULL
#define api_Response_DEFAULT NULL
#define api_Response_payload_empty_message_MSGTYPE api_EmptyMessage
#define api_Response_payload_ap_settings_MSGTYPE api_APSettings
#define api_Response_payload_ap_status_MSGTYPE api_APStatus
#define api_Response_payload_servo_settings_MSGTYPE api_ServoSettings
#define api_Response_payload_file_list_MSGTYPE api_FileList
#define api_Response_payload_wifi_settings_MSGTYPE api_WifiSettings
#define api_Response_payload_wifi_network_list_MSGTYPE api_WifiNetworkList
#define api_Response_payload_wifi_status_MSGTYPE api_WifiStatus
#define api_Response_payload_camera_settings_MSGTYPE api_CameraSettings
#define api_Response_payload_mdns_settings_MSGTYPE api_MDNSSettings
#define api_Response_payload_mdns_status_MSGTYPE api_MDNSStatus
#define api_Response_payload_mdns_query_response_MSGTYPE api_MDNSQueryResponse
#define api_Response_payload_peripheral_settings_MSGTYPE api_PeripheralSettings

extern const pb_msgdesc_t api_EmptyMessage_msg;
extern const pb_msgdesc_t api_APSettings_msg;
extern const pb_msgdesc_t api_APStatus_msg;
extern const pb_msgdesc_t api_APSettingsRequest_msg;
extern const pb_msgdesc_t api_APStatusRequest_msg;
extern const pb_msgdesc_t api_Servo_msg;
extern const pb_msgdesc_t api_ServoSettings_msg;
extern const pb_msgdesc_t api_ServoSettingsRequest_msg;
extern const pb_msgdesc_t api_WifiNetwork_msg;
extern const pb_msgdesc_t api_WifiSettings_msg;
extern const pb_msgdesc_t api_WifiSettingsRequest_msg;
extern const pb_msgdesc_t api_WifiNetworkScan_msg;
extern const pb_msgdesc_t api_WifiNetworkList_msg;
extern const pb_msgdesc_t api_WifiStatus_msg;
extern const pb_msgdesc_t api_CameraSettings_msg;
extern const pb_msgdesc_t api_CameraSettingsRequest_msg;
extern const pb_msgdesc_t api_MDNSTxtRecord_msg;
extern const pb_msgdesc_t api_MDNSServiceDef_msg;
extern const pb_msgdesc_t api_MDNSSettings_msg;
extern const pb_msgdesc_t api_MDNSStatus_msg;
extern const pb_msgdesc_t api_MDNSSettingsRequest_msg;
extern const pb_msgdesc_t api_MDNSStatusRequest_msg;
extern const pb_msgdesc_t api_MDNSQueryRequest_msg;
extern const pb_msgdesc_t api_MDNSQueryResult_msg;
extern const pb_msgdesc_t api_MDNSQueryResponse_msg;
extern const pb_msgdesc_t api_PinConfig_msg;
extern const pb_msgdesc_t api_PeripheralSettings_msg;
extern const pb_msgdesc_t api_PeripheralSettingsRequest_msg;
extern const pb_msgdesc_t api_FileEntry_msg;
extern const pb_msgdesc_t api_FileList_msg;
extern const pb_msgdesc_t api_FileListRequest_msg;
extern const pb_msgdesc_t api_FileDeleteRequest_msg;
extern const pb_msgdesc_t api_FileEditRequest_msg;
extern const pb_msgdesc_t api_FileMkdirRequest_msg;
extern const pb_msgdesc_t api_Request_msg;
extern const pb_msgdesc_t api_Response_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define api_EmptyMessage_fields &api_EmptyMessage_msg
#define api_APSettings_fields &api_APSettings_msg
#define api_APStatus_fields &api_APStatus_msg
#define api_APSettingsRequest_fields &api_APSettingsRequest_msg
#define api_APStatusRequest_fields &api_APStatusRequest_msg
#define api_Servo_fields &api_Servo_msg
#define api_ServoSettings_fields &api_ServoSettings_msg
#define api_ServoSettingsRequest_fields &api_ServoSettingsRequest_msg
#define api_WifiNetwork_fields &api_WifiNetwork_msg
#define api_WifiSettings_fields &api_WifiSettings_msg
#define api_WifiSettingsRequest_fields &api_WifiSettingsRequest_msg
#define api_WifiNetworkScan_fields &api_WifiNetworkScan_msg
#define api_WifiNetworkList_fields &api_WifiNetworkList_msg
#define api_WifiStatus_fields &api_WifiStatus_msg
#define api_CameraSettings_fields &api_CameraSettings_msg
#define api_CameraSettingsRequest_fields &api_CameraSettingsRequest_msg
#define api_MDNSTxtRecord_fields &api_MDNSTxtRecord_msg
#define api_MDNSServiceDef_fields &api_MDNSServiceDef_msg
#define api_MDNSSettings_fields &api_MDNSSettings_msg
#define api_MDNSStatus_fields &api_MDNSStatus_msg
#define api_MDNSSettingsRequest_fields &api_MDNSSettingsRequest_msg
#define api_MDNSStatusRequest_fields &api_MDNSStatusRequest_msg
#define api_MDNSQueryRequest_fields &api_MDNSQueryRequest_msg
#define api_MDNSQueryResult_fields &api_MDNSQueryResult_msg
#define api_MDNSQueryResponse_fields &api_MDNSQueryResponse_msg
#define api_PinConfig_fields &api_PinConfig_msg
#define api_PeripheralSettings_fields &api_PeripheralSettings_msg
#define api_PeripheralSettingsRequest_fields &api_PeripheralSettingsRequest_msg
#define api_FileEntry_fields &api_FileEntry_msg
#define api_FileList_fields &api_FileList_msg
#define api_FileListRequest_fields &api_FileListRequest_msg
#define api_FileDeleteRequest_fields &api_FileDeleteRequest_msg
#define api_FileEditRequest_fields &api_FileEditRequest_msg
#define api_FileMkdirRequest_fields &api_FileMkdirRequest_msg
#define api_Request_fields &api_Request_msg
#define api_Response_fields &api_Response_msg

/* Maximum encoded size of messages (where known) */
/* api_WifiNetworkList_size depends on runtime parameters */
/* api_FileEntry_size depends on runtime parameters */
/* api_FileList_size depends on runtime parameters */
/* api_FileEditRequest_size depends on runtime parameters */
/* api_Request_size depends on runtime parameters */
/* api_Response_size depends on runtime parameters */
#define API_API_PB_H_MAX_SIZE                    api_MDNSStatus_size
#define api_APSettingsRequest_size               0
#define api_APSettings_size                      133
#define api_APStatusRequest_size                 0
#define api_APStatus_size                        33
#define api_CameraSettingsRequest_size           0
#define api_CameraSettings_size                  220
#define api_EmptyMessage_size                    0
#define api_FileDeleteRequest_size               130
#define api_FileListRequest_size                 0
#define api_FileMkdirRequest_size                130
#define api_MDNSQueryRequest_size                26
#define api_MDNSQueryResponse_size               1920
#define api_MDNSQueryResult_size                 118
#define api_MDNSServiceDef_size                  432
#define api_MDNSSettingsRequest_size             0
#define api_MDNSSettings_size                    2239
#define api_MDNSStatusRequest_size               0
#define api_MDNSStatus_size                      2241
#define api_MDNSTxtRecord_size                   98
#define api_PeripheralSettingsRequest_size       0
#define api_PeripheralSettings_size              2081
#define api_PinConfig_size                       62
#define api_ServoSettingsRequest_size            0
#define api_ServoSettings_size                   468
#define api_Servo_size                           37
#define api_WifiNetworkScan_size                 76
#define api_WifiNetwork_size                     132
#define api_WifiSettingsRequest_size             0
#define api_WifiSettings_size                    717
#define api_WifiStatus_size                      125

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
