/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SOCKET_MESSAGE_FILESYSTEM_PB_H_INCLUDED
#define PB_SOCKET_MESSAGE_FILESYSTEM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _socket_message_File {
    char name[256];
    uint32_t size;
} socket_message_File;

/* Represents a single directory entry (metadata only) */
typedef struct _socket_message_Directory {
    char name[256];
} socket_message_Directory;

/* Delete a file or directory */
typedef struct _socket_message_FSDeleteRequest {
    char path[256];
} socket_message_FSDeleteRequest;

typedef struct _socket_message_FSDeleteResponse {
    bool success;
    char error[128];
} socket_message_FSDeleteResponse;

/* Create directory */
typedef struct _socket_message_FSMkdirRequest {
    char path[256];
} socket_message_FSMkdirRequest;

typedef struct _socket_message_FSMkdirResponse {
    bool success;
    char error[128];
} socket_message_FSMkdirResponse;

/* List files/directories */
typedef struct _socket_message_FSListRequest {
    char path[256];
} socket_message_FSListRequest;

typedef struct _socket_message_FSListResponse {
    bool success;
    char error[128];
    pb_size_t files_count;
    socket_message_File files[20];
    pb_size_t directories_count;
    socket_message_Directory directories[20];
} socket_message_FSListResponse;

typedef struct _socket_message_FSDownloadRequest {
    char path[256]; /* File path on ESP to download */
} socket_message_FSDownloadRequest;

typedef struct _socket_message_FSDownloadMetadata {
    uint32_t transfer_id; /* Transfer identifier */
    bool success; /* True if file exists and is readable */
    char error[128]; /* Error message if failed */
    uint32_t file_size; /* Total file size in bytes */
    uint32_t total_chunks; /* Total number of chunks to expect */
} socket_message_FSDownloadMetadata;

typedef PB_BYTES_ARRAY_T(16384) socket_message_FSDownloadData_data_t;
typedef struct _socket_message_FSDownloadData {
    uint32_t transfer_id; /* Transfer identifier */
    uint32_t chunk_index; /* Which chunk this is (0-based) */
    socket_message_FSDownloadData_data_t data; /* Chunk data (up to 16KB) */
} socket_message_FSDownloadData;

typedef struct _socket_message_FSDownloadComplete {
    uint32_t transfer_id;
    bool success;
    char error[128]; /* Error message if failed */
    uint32_t total_chunks; /* Total chunks that were sent */
    uint32_t file_size; /* Total file size in bytes */
} socket_message_FSDownloadComplete;

typedef struct _socket_message_FSUploadStart {
    char path[256]; /* Destination path on ESP */
    uint32_t file_size; /* Total file size in bytes */
    uint32_t total_chunks; /* Total number of chunks to expect */
} socket_message_FSUploadStart;

typedef struct _socket_message_FSUploadStartResponse {
    bool success;
    char error[128];
    uint32_t transfer_id; /* Unique ID for this transfer */
} socket_message_FSUploadStartResponse;

typedef PB_BYTES_ARRAY_T(16384) socket_message_FSUploadData_data_t;
typedef struct _socket_message_FSUploadData {
    uint32_t transfer_id; /* Transfer identifier */
    uint32_t chunk_index; /* Which chunk this is (0-based) */
    socket_message_FSUploadData_data_t data; /* Chunk data (up to 16KB) */
} socket_message_FSUploadData;

typedef struct _socket_message_FSUploadComplete {
    uint32_t transfer_id;
    bool success;
    char error[128]; /* Error message if failed */
    uint32_t chunks_received; /* Number of chunks actually received */
} socket_message_FSUploadComplete;

typedef struct _socket_message_FSCancelTransfer {
    uint32_t transfer_id;
} socket_message_FSCancelTransfer;

typedef struct _socket_message_FSCancelTransferResponse {
    uint32_t transfer_id;
    bool success;
} socket_message_FSCancelTransferResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define socket_message_File_init_default         {"", 0}
#define socket_message_Directory_init_default    {""}
#define socket_message_FSDeleteRequest_init_default {""}
#define socket_message_FSDeleteResponse_init_default {0, ""}
#define socket_message_FSMkdirRequest_init_default {""}
#define socket_message_FSMkdirResponse_init_default {0, ""}
#define socket_message_FSListRequest_init_default {""}
#define socket_message_FSListResponse_init_default {0, "", 0, {socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default, socket_message_File_init_default}, 0, {socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default, socket_message_Directory_init_default}}
#define socket_message_FSDownloadRequest_init_default {""}
#define socket_message_FSDownloadMetadata_init_default {0, 0, "", 0, 0}
#define socket_message_FSDownloadData_init_default {0, 0, {0, {0}}}
#define socket_message_FSDownloadComplete_init_default {0, 0, "", 0, 0}
#define socket_message_FSUploadStart_init_default {"", 0, 0}
#define socket_message_FSUploadStartResponse_init_default {0, "", 0}
#define socket_message_FSUploadData_init_default {0, 0, {0, {0}}}
#define socket_message_FSUploadComplete_init_default {0, 0, "", 0}
#define socket_message_FSCancelTransfer_init_default {0}
#define socket_message_FSCancelTransferResponse_init_default {0, 0}
#define socket_message_File_init_zero            {"", 0}
#define socket_message_Directory_init_zero       {""}
#define socket_message_FSDeleteRequest_init_zero {""}
#define socket_message_FSDeleteResponse_init_zero {0, ""}
#define socket_message_FSMkdirRequest_init_zero  {""}
#define socket_message_FSMkdirResponse_init_zero {0, ""}
#define socket_message_FSListRequest_init_zero   {""}
#define socket_message_FSListResponse_init_zero  {0, "", 0, {socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero, socket_message_File_init_zero}, 0, {socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero, socket_message_Directory_init_zero}}
#define socket_message_FSDownloadRequest_init_zero {""}
#define socket_message_FSDownloadMetadata_init_zero {0, 0, "", 0, 0}
#define socket_message_FSDownloadData_init_zero  {0, 0, {0, {0}}}
#define socket_message_FSDownloadComplete_init_zero {0, 0, "", 0, 0}
#define socket_message_FSUploadStart_init_zero   {"", 0, 0}
#define socket_message_FSUploadStartResponse_init_zero {0, "", 0}
#define socket_message_FSUploadData_init_zero    {0, 0, {0, {0}}}
#define socket_message_FSUploadComplete_init_zero {0, 0, "", 0}
#define socket_message_FSCancelTransfer_init_zero {0}
#define socket_message_FSCancelTransferResponse_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define socket_message_File_name_tag             10
#define socket_message_File_size_tag             20
#define socket_message_Directory_name_tag        1
#define socket_message_FSDeleteRequest_path_tag  1
#define socket_message_FSDeleteResponse_success_tag 1
#define socket_message_FSDeleteResponse_error_tag 2
#define socket_message_FSMkdirRequest_path_tag   1
#define socket_message_FSMkdirResponse_success_tag 1
#define socket_message_FSMkdirResponse_error_tag 2
#define socket_message_FSListRequest_path_tag    1
#define socket_message_FSListResponse_success_tag 1
#define socket_message_FSListResponse_error_tag  2
#define socket_message_FSListResponse_files_tag  3
#define socket_message_FSListResponse_directories_tag 4
#define socket_message_FSDownloadRequest_path_tag 1
#define socket_message_FSDownloadMetadata_transfer_id_tag 1
#define socket_message_FSDownloadMetadata_success_tag 2
#define socket_message_FSDownloadMetadata_error_tag 3
#define socket_message_FSDownloadMetadata_file_size_tag 4
#define socket_message_FSDownloadMetadata_total_chunks_tag 5
#define socket_message_FSDownloadData_transfer_id_tag 1
#define socket_message_FSDownloadData_chunk_index_tag 2
#define socket_message_FSDownloadData_data_tag   3
#define socket_message_FSDownloadComplete_transfer_id_tag 1
#define socket_message_FSDownloadComplete_success_tag 2
#define socket_message_FSDownloadComplete_error_tag 3
#define socket_message_FSDownloadComplete_total_chunks_tag 4
#define socket_message_FSDownloadComplete_file_size_tag 5
#define socket_message_FSUploadStart_path_tag    1
#define socket_message_FSUploadStart_file_size_tag 2
#define socket_message_FSUploadStart_total_chunks_tag 3
#define socket_message_FSUploadStartResponse_success_tag 1
#define socket_message_FSUploadStartResponse_error_tag 2
#define socket_message_FSUploadStartResponse_transfer_id_tag 3
#define socket_message_FSUploadData_transfer_id_tag 1
#define socket_message_FSUploadData_chunk_index_tag 2
#define socket_message_FSUploadData_data_tag     3
#define socket_message_FSUploadComplete_transfer_id_tag 1
#define socket_message_FSUploadComplete_success_tag 2
#define socket_message_FSUploadComplete_error_tag 3
#define socket_message_FSUploadComplete_chunks_received_tag 4
#define socket_message_FSCancelTransfer_transfer_id_tag 1
#define socket_message_FSCancelTransferResponse_transfer_id_tag 1
#define socket_message_FSCancelTransferResponse_success_tag 2

/* Struct field encoding specification for nanopb */
#define socket_message_File_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,             10) \
X(a, STATIC,   SINGULAR, UINT32,   size,             20)
#define socket_message_File_CALLBACK NULL
#define socket_message_File_DEFAULT NULL

#define socket_message_Directory_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1)
#define socket_message_Directory_CALLBACK NULL
#define socket_message_Directory_DEFAULT NULL

#define socket_message_FSDeleteRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   path,              1)
#define socket_message_FSDeleteRequest_CALLBACK NULL
#define socket_message_FSDeleteRequest_DEFAULT NULL

#define socket_message_FSDeleteResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   error,             2)
#define socket_message_FSDeleteResponse_CALLBACK NULL
#define socket_message_FSDeleteResponse_DEFAULT NULL

#define socket_message_FSMkdirRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   path,              1)
#define socket_message_FSMkdirRequest_CALLBACK NULL
#define socket_message_FSMkdirRequest_DEFAULT NULL

#define socket_message_FSMkdirResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   error,             2)
#define socket_message_FSMkdirResponse_CALLBACK NULL
#define socket_message_FSMkdirResponse_DEFAULT NULL

#define socket_message_FSListRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   path,              1)
#define socket_message_FSListRequest_CALLBACK NULL
#define socket_message_FSListRequest_DEFAULT NULL

#define socket_message_FSListResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   error,             2) \
X(a, STATIC,   REPEATED, MESSAGE,  files,             3) \
X(a, STATIC,   REPEATED, MESSAGE,  directories,       4)
#define socket_message_FSListResponse_CALLBACK NULL
#define socket_message_FSListResponse_DEFAULT NULL
#define socket_message_FSListResponse_files_MSGTYPE socket_message_File
#define socket_message_FSListResponse_directories_MSGTYPE socket_message_Directory

#define socket_message_FSDownloadRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   path,              1)
#define socket_message_FSDownloadRequest_CALLBACK NULL
#define socket_message_FSDownloadRequest_DEFAULT NULL

#define socket_message_FSDownloadMetadata_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   transfer_id,       1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, STATIC,   SINGULAR, STRING,   error,             3) \
X(a, STATIC,   SINGULAR, UINT32,   file_size,         4) \
X(a, STATIC,   SINGULAR, UINT32,   total_chunks,      5)
#define socket_message_FSDownloadMetadata_CALLBACK NULL
#define socket_message_FSDownloadMetadata_DEFAULT NULL

#define socket_message_FSDownloadData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   transfer_id,       1) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       2) \
X(a, STATIC,   SINGULAR, BYTES,    data,              3)
#define socket_message_FSDownloadData_CALLBACK NULL
#define socket_message_FSDownloadData_DEFAULT NULL

#define socket_message_FSDownloadComplete_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   transfer_id,       1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, STATIC,   SINGULAR, STRING,   error,             3) \
X(a, STATIC,   SINGULAR, UINT32,   total_chunks,      4) \
X(a, STATIC,   SINGULAR, UINT32,   file_size,         5)
#define socket_message_FSDownloadComplete_CALLBACK NULL
#define socket_message_FSDownloadComplete_DEFAULT NULL

#define socket_message_FSUploadStart_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   path,              1) \
X(a, STATIC,   SINGULAR, UINT32,   file_size,         2) \
X(a, STATIC,   SINGULAR, UINT32,   total_chunks,      3)
#define socket_message_FSUploadStart_CALLBACK NULL
#define socket_message_FSUploadStart_DEFAULT NULL

#define socket_message_FSUploadStartResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, UINT32,   transfer_id,       3)
#define socket_message_FSUploadStartResponse_CALLBACK NULL
#define socket_message_FSUploadStartResponse_DEFAULT NULL

#define socket_message_FSUploadData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   transfer_id,       1) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_index,       2) \
X(a, STATIC,   SINGULAR, BYTES,    data,              3)
#define socket_message_FSUploadData_CALLBACK NULL
#define socket_message_FSUploadData_DEFAULT NULL

#define socket_message_FSUploadComplete_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   transfer_id,       1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, STATIC,   SINGULAR, STRING,   error,             3) \
X(a, STATIC,   SINGULAR, UINT32,   chunks_received,   4)
#define socket_message_FSUploadComplete_CALLBACK NULL
#define socket_message_FSUploadComplete_DEFAULT NULL

#define socket_message_FSCancelTransfer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   transfer_id,       1)
#define socket_message_FSCancelTransfer_CALLBACK NULL
#define socket_message_FSCancelTransfer_DEFAULT NULL

#define socket_message_FSCancelTransferResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   transfer_id,       1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2)
#define socket_message_FSCancelTransferResponse_CALLBACK NULL
#define socket_message_FSCancelTransferResponse_DEFAULT NULL

extern const pb_msgdesc_t socket_message_File_msg;
extern const pb_msgdesc_t socket_message_Directory_msg;
extern const pb_msgdesc_t socket_message_FSDeleteRequest_msg;
extern const pb_msgdesc_t socket_message_FSDeleteResponse_msg;
extern const pb_msgdesc_t socket_message_FSMkdirRequest_msg;
extern const pb_msgdesc_t socket_message_FSMkdirResponse_msg;
extern const pb_msgdesc_t socket_message_FSListRequest_msg;
extern const pb_msgdesc_t socket_message_FSListResponse_msg;
extern const pb_msgdesc_t socket_message_FSDownloadRequest_msg;
extern const pb_msgdesc_t socket_message_FSDownloadMetadata_msg;
extern const pb_msgdesc_t socket_message_FSDownloadData_msg;
extern const pb_msgdesc_t socket_message_FSDownloadComplete_msg;
extern const pb_msgdesc_t socket_message_FSUploadStart_msg;
extern const pb_msgdesc_t socket_message_FSUploadStartResponse_msg;
extern const pb_msgdesc_t socket_message_FSUploadData_msg;
extern const pb_msgdesc_t socket_message_FSUploadComplete_msg;
extern const pb_msgdesc_t socket_message_FSCancelTransfer_msg;
extern const pb_msgdesc_t socket_message_FSCancelTransferResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define socket_message_File_fields &socket_message_File_msg
#define socket_message_Directory_fields &socket_message_Directory_msg
#define socket_message_FSDeleteRequest_fields &socket_message_FSDeleteRequest_msg
#define socket_message_FSDeleteResponse_fields &socket_message_FSDeleteResponse_msg
#define socket_message_FSMkdirRequest_fields &socket_message_FSMkdirRequest_msg
#define socket_message_FSMkdirResponse_fields &socket_message_FSMkdirResponse_msg
#define socket_message_FSListRequest_fields &socket_message_FSListRequest_msg
#define socket_message_FSListResponse_fields &socket_message_FSListResponse_msg
#define socket_message_FSDownloadRequest_fields &socket_message_FSDownloadRequest_msg
#define socket_message_FSDownloadMetadata_fields &socket_message_FSDownloadMetadata_msg
#define socket_message_FSDownloadData_fields &socket_message_FSDownloadData_msg
#define socket_message_FSDownloadComplete_fields &socket_message_FSDownloadComplete_msg
#define socket_message_FSUploadStart_fields &socket_message_FSUploadStart_msg
#define socket_message_FSUploadStartResponse_fields &socket_message_FSUploadStartResponse_msg
#define socket_message_FSUploadData_fields &socket_message_FSUploadData_msg
#define socket_message_FSUploadComplete_fields &socket_message_FSUploadComplete_msg
#define socket_message_FSCancelTransfer_fields &socket_message_FSCancelTransfer_msg
#define socket_message_FSCancelTransferResponse_fields &socket_message_FSCancelTransferResponse_msg

/* Maximum encoded size of messages (where known) */
#define SOCKET_MESSAGE_FILESYSTEM_PB_H_MAX_SIZE  socket_message_FSDownloadData_size
#define socket_message_Directory_size            258
#define socket_message_FSCancelTransferResponse_size 8
#define socket_message_FSCancelTransfer_size     6
#define socket_message_FSDeleteRequest_size      258
#define socket_message_FSDeleteResponse_size     132
#define socket_message_FSDownloadComplete_size   150
#define socket_message_FSDownloadData_size       16400
#define socket_message_FSDownloadMetadata_size   150
#define socket_message_FSDownloadRequest_size    258
#define socket_message_FSListRequest_size        258
#define socket_message_FSListResponse_size       10712
#define socket_message_FSMkdirRequest_size       258
#define socket_message_FSMkdirResponse_size      132
#define socket_message_FSUploadComplete_size     144
#define socket_message_FSUploadData_size         16400
#define socket_message_FSUploadStartResponse_size 138
#define socket_message_FSUploadStart_size        270
#define socket_message_File_size                 265

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
