/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "filesystem.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(socket_message_File, socket_message_File, 2)


PB_BIND(socket_message_Directory, socket_message_Directory, 2)


PB_BIND(socket_message_FSDeleteRequest, socket_message_FSDeleteRequest, 2)


PB_BIND(socket_message_FSDeleteResponse, socket_message_FSDeleteResponse, AUTO)


PB_BIND(socket_message_FSMkdirRequest, socket_message_FSMkdirRequest, 2)


PB_BIND(socket_message_FSMkdirResponse, socket_message_FSMkdirResponse, AUTO)


PB_BIND(socket_message_FSListRequest, socket_message_FSListRequest, 2)


PB_BIND(socket_message_FSListResponse, socket_message_FSListResponse, 4)


PB_BIND(socket_message_FSDownloadRequest, socket_message_FSDownloadRequest, 2)


PB_BIND(socket_message_FSDownloadMetadata, socket_message_FSDownloadMetadata, AUTO)


PB_BIND(socket_message_FSDownloadData, socket_message_FSDownloadData, 4)


PB_BIND(socket_message_FSDownloadComplete, socket_message_FSDownloadComplete, AUTO)


PB_BIND(socket_message_FSUploadStart, socket_message_FSUploadStart, 2)


PB_BIND(socket_message_FSUploadStartResponse, socket_message_FSUploadStartResponse, AUTO)


PB_BIND(socket_message_FSUploadData, socket_message_FSUploadData, 4)


PB_BIND(socket_message_FSUploadComplete, socket_message_FSUploadComplete, AUTO)


PB_BIND(socket_message_FSCancelTransfer, socket_message_FSCancelTransfer, AUTO)


PB_BIND(socket_message_FSCancelTransferResponse, socket_message_FSCancelTransferResponse, AUTO)



